# Site
repository: Bhati1998/lokesh.github.io
favicon: images/favicon.ico

# Personal info
name: Lokesh Bhati
title: VLSI Enginner
email: lokeshbhati1998@gmail.com
website: www.github.com/Bhati1998/lokesh.github.io

# Social links
twitter_username: lokesh_bhati_
github_username:  Bhati1998
# dribbble_username: lokesh_bhati_
# facebook_username: lokesh_bhati_
# flickr_username: lokesh_bhati_
instagram_username: lokesh_bhati_
linkedin_username: lokesh-bhati
# pinterest_username: lokesh-bhati
youtube_username: Lokesh Bhati
# googleplus_username: lokesh-bhati

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Lokesh Bhati and I'm a VLSI Verification Enginner. As well as embedded systems I also have experience making webpages and android apps. I have worked at a Aarmontech companie gaining teamwork and leadership skills.

  I am most skilled in: <mark>IOT</mark> and <mark>Eating Pizza :)</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in electronics &communication engineering some of my other interests and hobbies are:
   - Sketching
   - Gaming

# Footer
footer_show_references: true

# Build settings
remote_theme: jekyll/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
